#!/usr/bin/env node
/**
 * M10 PWA-readiness gate (build-artifact proxy for the Lighthouse-PWA audit).
 *
 * Asserts the installable-app artifacts a production build must emit:
 *   - a generated Serwist service worker (public/sw.js) of non-trivial size,
 *   - the app icon asset the manifest points at,
 *   - the manifest route compiled into the build.
 *
 * The *served* manifest's field-level validity + SW registration are asserted at runtime by
 * e2e/pwa.spec.ts; full Lighthouse scoring is documented in LAUNCH_READINESS.md. Run after build:
 *   node scripts/check-pwa.mjs
 */
import { existsSync, statSync, readdirSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(process.cwd());
const checks = [];

function check(label, ok, detail = '') {
  checks.push({ label, ok, detail });
}

// 1. Service worker generated by Serwist.
const swPath = join(ROOT, 'public', 'sw.js');
const swOk = existsSync(swPath) && statSync(swPath).size > 10 * 1024;
check(
  'Service worker (public/sw.js)',
  swOk,
  swOk ? `${(statSync(swPath).size / 1024).toFixed(1)} KB` : 'missing or too small — did the PWA build run?',
);

// 2. App icon the manifest references.
const iconPath = join(ROOT, 'public', 'icons', 'icon.svg');
check('App icon (public/icons/icon.svg)', existsSync(iconPath), existsSync(iconPath) ? '' : 'missing');

// 3. Manifest route compiled into the build.
const appServer = join(ROOT, '.next', 'server', 'app');
let manifestBuilt = false;
if (existsSync(appServer)) {
  manifestBuilt = readdirSync(appServer).some((e) => e.startsWith('manifest.webmanifest'));
}
check(
  'Manifest route (.next/server/app/manifest.webmanifest*)',
  manifestBuilt,
  manifestBuilt ? '' : 'not found — run `next build` with PWA enabled first',
);

console.log('\nPWA readiness');
console.log('─────────────');
for (const c of checks) {
  console.log(`  ${c.ok ? '✔' : '✖'} ${c.label}${c.detail ? `  — ${c.detail}` : ''}`);
}

const failed = checks.filter((c) => !c.ok);
if (failed.length) {
  console.error(`\n✖ PWA readiness FAILED (${failed.length} check(s)).\n`);
  process.exit(1);
}
console.log('\n✔ PWA artifacts present. Run Lighthouse for the full score (see LAUNCH_READINESS.md).\n');
